### ISSUE TITLE
Sync: Program does not produce a toml file for `grains`

### ISSUE THREAD

**Issue by ee7** [exercism/canonical-data-syncer#39]
### Example
On a track that contains the `grains` exercise, but lacks a `exercises/grains/.meta/tests.toml` file, run:
```
canonical_data_syncer
```

### Current behaviour
The program does not create a `tests.toml` file for `grains`, but we see
```
All exercises are synced!
```

### Expected behaviour
The program should create a `tests.toml` file for `grains`.

The expected contents are:
```toml
[canonical-tests]

# 1
"9fbde8de-36b2-49de-baf2-cd42d6f28405" = true

# 2
"ee1f30c2-01d8-4298-b25d-c677331b5e6d" = true

# 3
"10f45584-2fc3-4875-8ec6-666065d1163b" = true

# 4
"a7cbe01b-36f4-4601-b053-c5f6ae055170" = true

# 16
"c50acc89-8535-44e4-918f-b848ad2817d4" = true

# 32
"acd81b46-c2ad-4951-b848-80d15ed5a04f" = true

# 64
"c73b470a-5efb-4d53-9ac6-c5f6487f227b" = true

# square 0 raises an exception
"1d47d832-3e85-4974-9466-5bd35af484e3" = true

# negative square raises an exception
"61974483-eeb2-465e-be54-ca5dde366453" = true

# square greater than 64 raises an exception
"a95e4374-f32c-45a7-a10d-ffec475c012f" = true

# returns the total number of grains on the board
"6eb07385-3659-4b45-a6be-9dc474222750" = true
```

### Discussion
The cause is here:
https://github.com/exercism/canonical-data-syncer/blob/6e162f70b6944e87ffc2ae60314c38f06459541d/src/probspecs.nim#L80-L84

I remember running into this problem myself. It's because `grains` contains two test cases with large numbers ([here](https://github.com/exercism/problem-specifications/blob/5c7d01519ad9317cbdb7727c0e0f302d0bfeae07/exercises/grains/canonical-data.json#L65-L73) and [here](https://github.com/exercism/problem-specifications/blob/5c7d01519ad9317cbdb7727c0e0f302d0bfeae07/exercises/grains/canonical-data.json#L103-L109)).

The first number is one larger than we can store in a 64-bit signed integer, so it causes an error (and the second number is the maximum that can be stored in a 64-bit **unsigned** integer).
